INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(1, 0, NULL, '2021-07-01 08:00:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(2, 1, NULL, '2021-07-01 08:30:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(3, 0, NULL, '2021-07-03 07:30:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(4, 0, NULL, '2021-07-03 08:00:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(5, 1, NULL, '2021-07-03 08:30:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(6, 0, NULL, '2021-07-01 09:00:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(7, 0, NULL, '2021-07-01 10:00:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(8, 0, NULL, '2021-07-01 12:00:00', 'NO_REPEAT', 'TITLE 1', NULL, 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(9, 1, NULL, '2021-07-04 08:00:00', 'NO_REPEAT', 'TITLE 1', '2021-07-10 08:00:00', 'NO_REPEAT', NULL, 'NO_REMINDER');

INSERT INTO EVENTS
(ID, ALL_DAY, DESCRIPTION, START_DATE, START_REPEAT, TITLE, END_DATE, END_REPEAT, LOCATION, REMINDER)
VALUES
(10, 1, NULL, '2021-07-04 09:00:00', 'NO_REPEAT', 'TITLE 1', '2021-07-06 09:00:00', 'NO_REPEAT', NULL, 'NO_REMINDER');




